from fpdf import FPDF
import matplotlib.pyplot as plt
import os
import config as cfg

# VISUAL SETTINGS
PRIMARY_COLOR = (50, 80, 160) # Medical Blue
SECONDARY_COLOR = (240, 240, 240) # Light Gray
TEXT_COLOR = (40, 40, 40)

class ModernReport(FPDF):
    def header(self):
        # Top Bar
        self.set_fill_color(*PRIMARY_COLOR)
        self.rect(0, 0, 210, 20, 'F')
        # Title
        self.set_font('Arial', 'B', 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'TRACEMIND | Clinical Analysis Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by TraceMind AI', 0, 0, 'C')

def generate_charts(stats):
    """ Generates a clean Horizontal Bar Chart """
    labels = list(stats.keys())
    values = list(stats.values())
    
    # Sort for better readability
    sorted_pairs = sorted(zip(values, labels))
    values = [x[0] for x in sorted_pairs]
    labels = [x[1] for x in sorted_pairs]
    
    plt.figure(figsize=(8, 4))
    bars = plt.barh(labels, values, color='#4a90e2')
    
    for bar in bars:
        width = bar.get_width()
        plt.text(width + 1, bar.get_y() + bar.get_height()/2, 
                 f'{width}%', ha='left', va='center', fontsize=10)
        
    plt.title('Emotional State Distribution', fontsize=12)
    plt.xlim(0, 105)
    plt.tight_layout()
    
    filename = "temp_chart_bar.png"
    plt.savefig(filename, dpi=300)
    plt.close()
    return filename

def create_pdf(patient, results, output_filename=None):
    # If no filename passed, use default from config
    if output_filename is None:
        output_filename = cfg.REPORT_FILENAME

    pdf = ModernReport()
    pdf.add_page()
    pdf.set_text_color(*TEXT_COLOR)

    # --- SECTION 1: PATIENT DEMOGRAPHICS ---
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(*SECONDARY_COLOR)
    pdf.cell(0, 10, "  1. PATIENT DEMOGRAPHICS", 0, 1, 'L', 1)
    
    pdf.ln(4)
    pdf.set_font('Arial', '', 10)
    
    # Row 1: Name and ID
    pdf.cell(30, 8, "Patient Name:", 0, 0)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(70, 8, patient['name'], 0, 0)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(25, 8, "Patient ID:", 0, 0)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(40, 8, patient['id'], 0, 1)
    
    # Row 2: Age, Gender, Date
    pdf.set_font('Arial', '', 10)
    pdf.cell(30, 8, "Age / Gender:", 0, 0)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(70, 8, f"{patient['age']} Y / {patient['gender']}", 0, 0)

    pdf.set_font('Arial', '', 10)
    pdf.cell(25, 8, "Date:", 0, 0)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(40, 8, patient['date'], 0, 1)
    
    pdf.ln(2)
    pdf.set_font('Arial', '', 10)
    pdf.cell(30, 8, "Session Notes:", 0, 0)
    pdf.multi_cell(0, 8, patient['notes'])
    pdf.ln(5)

    # --- SECTION 2: EXECUTIVE SUMMARY ---
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(*SECONDARY_COLOR)
    pdf.cell(0, 10, "  2. EXECUTIVE SUMMARY", 0, 1, 'L', 1)
    pdf.ln(4)
    
    dom = max(results['stats'], key=results['stats'].get)
    score = results['stats'][dom]
    
    pdf.set_font('Arial', '', 10)
    pdf.write(5, "The subject displayed a dominant emotional state of ")
    pdf.set_font('Arial', 'B', 10)
    pdf.set_text_color(*PRIMARY_COLOR)
    pdf.write(5, f"{dom.upper()} ({score}%)")
    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font('Arial', '', 10)
    pdf.write(5, ".\n\n")
    
    if dom in ['Angry', 'Fear', 'Sad']:
        pdf.set_text_color(200, 50, 50)
        pdf.write(5, "NOTE: High negative valence detected. Clinical review recommended.")
        pdf.set_text_color(*TEXT_COLOR)
    else:
        pdf.write(5, "The subject appeared predominantly engaged and stable.")
    
    pdf.ln(10)

    # --- SECTION 3: VISUAL CHART ---
    chart_file = generate_charts(results['stats'])
    pdf.image(chart_file, x=15, w=180)
    os.remove(chart_file)
    pdf.ln(5)

    # --- SECTION 4: TIMELINE TABLE ---
    pdf.add_page()
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(*SECONDARY_COLOR)
    pdf.cell(0, 10, "  3. TEMPORAL ANALYSIS (Timeline)", 0, 1, 'L', 1)
    pdf.ln(5)
    
    # Table Header
    pdf.set_font('Arial', 'B', 9)
    pdf.set_fill_color(*PRIMARY_COLOR)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(40, 8, "Time Interval", 1, 0, 'C', 1)
    pdf.cell(60, 8, "Dominant Emotion", 1, 0, 'C', 1)
    pdf.cell(40, 8, "Confidence Score", 1, 1, 'C', 1)
    
    # Table Rows
    pdf.set_font('Arial', '', 9)
    pdf.set_text_color(*TEXT_COLOR)
    
    fill = False
    for row in results['timeline']:
        if fill:
            pdf.set_fill_color(245, 245, 245)
        else:
            pdf.set_fill_color(255, 255, 255)
            
        pdf.cell(40, 8, row['time'], 1, 0, 'C', 1)
        
        # Color Warnings
        if row['emotion'] in ['Angry', 'Fear', 'Sad']:
            pdf.set_text_color(200, 50, 50)
            pdf.set_font('Arial', 'B', 9)
            pdf.cell(60, 8, row['emotion'], 1, 0, 'C', 1)
            pdf.set_font('Arial', '', 9)
            pdf.set_text_color(*TEXT_COLOR)
        else:
            pdf.cell(60, 8, row['emotion'], 1, 0, 'C', 1)
            
        pdf.cell(40, 8, f"{row['conf']}%", 1, 1, 'C', 1)
        fill = not fill

    pdf.output(output_filename)
    print(f"[Report] Generated: {output_filename}")